{% set name = "segregation" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segregation-{{ version }}.tar.gz
  sha256: fedd0e16413a1ef111404d18f5af9652cf47ee4a7fdaf1ad15e932b5034e4042

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - deprecation
    - geopandas >=0.9
    - joblib
    - libpysal
    - mapclassify
    - matplotlib-base
    - numpy
    - pandas
    - scikit-learn >=0.21.3
    - scipy
    - seaborn
    - tqdm
    - numba
    - pyproj >=3

test:
  imports:
    - segregation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Segregation Measures Framework in PySAL

  description: |
    The PySAL segregation module allow users to estimate several segregation measures and perform 
    inference for single measures and comparative inference in a concise way.
  doc_url: https://pysal.org/segregation/
  dev_url: https://github.com/pysal/segregation

extra:
  recipe-maintainers:
    - renanxcortes
    - sjsrey
    - knaaptime
    - ocefpaf
    - jGaboardi
    - martinfleis
