{% set name = "segregation" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pysal/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 815c3d2ede32fe9bbf1654160e22b1984385bbe5f6c231b927870ae494c9957c
 
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pandas
    - geopandas
    - matplotlib
    - scikit-learn
    - seaborn
    - numpy
    - scipy
    - libpysal

test:
  imports:
    - segregation

about:
  home: https://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Segregation Measures Framework in PySAL'

  description: |
    The PySAL segregation module allow users to estimate several segregation measures and perform 
    inference for single measures and comparative inference in a concise way.
  doc_url: http://segregation.readthedocs.io/
  dev_url: https://github.com/pysal/segregation

extra:
  recipe-maintainers:
    - renanxcortes
    - sjsrey
    - knaaptime
