{% set name = "segregation" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/segregation-{{ version }}.tar.gz
  sha256: e2a2e580818032f7924b871ee43257cfc684572305df3a9f27ff6e1d647643c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - deprecation
    - geopandas >=0.9
    - joblib
    - libpysal
    - mapclassify
    - matplotlib-base
    - numpy
    - pandas
    - scikit-learn >=0.21.3
    - scipy
    - seaborn
    - tqdm
    - numba
    - pyproj >=3

test:
  imports:
    - segregation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Segregation Measures Framework in PySAL

  description: |
    The PySAL segregation module allow users to estimate several segregation measures and perform 
    inference for single measures and comparative inference in a concise way.
  doc_url: https://pysal.org/segregation/
  dev_url: https://github.com/pysal/segregation

extra:
  recipe-maintainers:
    - renanxcortes
    - sjsrey
    - knaaptime
    - ocefpaf
    - jGaboardi
    - martinfleis
